export const siteConfig = {
  name: "ARZ Home Remodeling",
  owner: "",
  tagline: "Bathroom Remodeling in Chandler, AZ",
  description: "Bathroom remodeling in Chandler, Arizona. Walk-in showers, tub-to-shower conversions, tile, vanities, and master bath remodels. Free estimates.",
  foundedYear: null,
  googleReviewsCount: 0,
  googleRating: 0,
  warranty: "",
  url: "https://arzhomeremodeling.com",
  googleBusinessLink: "https://www.google.com/maps/search/?api=1&query=ARZ+Home+Remodeling+Chandler+AZ",
  phone: "(520) 569-3339",
  phoneClean: "+15205693339",
  email: "estimates@arzhomeremodeling.com",
  license: "",
  address: {
    street: "6710 W Chicago St",
    city: "Chandler",
    state: "AZ",
    zip: "85226",
    full: "6710 W Chicago St, Chandler, AZ 85226",
    coordinates: {
      lat: 33.3009334,
      lng: -111.9605964,
    },
  },
  zipCodes: ["85224", "85225", "85226", "85244", "85246", "85248", "85249", "85286"],
  hours: {
    weekdays: "9:00 AM - 8:00 PM CST",
    saturday: "9:00 AM - 8:00 PM CST",
    sunday: "Closed",
  },
  social: {
    facebook: "https://www.facebook.com/arzhomeremodeling",
    instagram: "https://www.instagram.com/arzhomeremodeling/",
    youtube: "https://youtube.com/arzhomeremodeling",
    linkedin: "https://www.linkedin.com/company/arz-home-remodeling/",
    twitter: "",
    pinterest: "",
  },
  navigation: [
    { name: "Home", href: "/" },
    { name: "About", href: "/about/" },
    { name: "Services", href: "/services/" },
    { name: "Blog", href: "/blog/" },
    { name: "Contact", href: "/contact/" },
  ],
  serviceAreas: [
    "Chandler",
    "Ahwatukee",
    "Sun Lakes",
    "Ocotillo",
    "Dobson Ranch",
    "Fulton Ranch",
    "Queen Creek",
    "Apache Junction",
    "Chandler Heights",
    "Andersen Springs",
    "Layton Lakes",
    "The Islands",
    "Pecos Ranch",
  ],
  umamiWebsiteId: "",
  umamiShareUrl: "",
};
